### ISSUE TITLE
spreadSheet : 기능정의서 제작

### ISSUE THREAD

**Issue by Ju-jh** [nail-dp-dev/nail-dp-dev-nextjs14#1]
- [ ]  Spread sheet 기능 정의서 완료할 것.

**Comment by lsh7465** [comment]
1. 피그마에 있는 와이어프레임을 참고하여 기능정의서에 대략적인 기능들을 작성함. 
    -> 5/27(월)에 팀원들과 더 상세히 다룰 예정

**Comment by Ju-jh** [comment]
![Image](https://github.com/nail-dp-dev/Nail_dp_dev_FE/assets/121030294/8662de41-dc26-4d22-bb90-37fe26b56389)

해당 이미지와 같이 기능정의서 Sheet 작성 완료.

**Comment by Ju-jh** [comment]
전체 파일 수정 완료
