### ISSUE TITLE
spreadSheet : API 명세서

### ISSUE THREAD

**Issue by LKW9** [nail-dp-dev/nail-dp-dev-nextjs14#3]

**Comment by Ju-jh** [comment]
![Image](https://github.com/nail-dp-dev/nail-dp-dev-nextjs14/assets/121030294/2755bebe-c42b-4e2e-a3b3-ed729aae001e)


백엔드와 협업하여 endpoint 설정 및 방식 결정

@nail-dp-dev/backend @nail-dp-dev/frontend
