### ISSUE TITLE
conf : CSS 협업 설정

### ISSUE THREAD

**Issue by Ju-jh** [nail-dp-dev/nail-dp-dev-nextjs14#6]
1. tailwind.config 설정 
 -> screens 설정 ( media query ).
 -> colors 설정.

2. globals.css 설정

**Comment by Ju-jh** [comment]
1. tailwind.config 설정
screens 설정 ( media query ).
![Image](https://github.com/nail-dp-dev/Nail_dp_dev_FE/assets/121030294/4b67599f-80bb-4df1-ba05-d5e37ed0ab82)

colors 설정.
![Image](https://github.com/nail-dp-dev/Nail_dp_dev_FE/assets/121030294/1187474c-c2e9-452f-879a-fe9c08cc1652)
 -> 인원들과 협의 후 추가 할 예정

2. globals.css 설정
![Image](https://github.com/nail-dp-dev/Nail_dp_dev_FE/assets/121030294/56c6764c-7ffe-4b23-bcaf-9137e174f1af)

@tailwind 인식 문제
-> PostCSS Language Support Extends 설치하여 해결
![Image](https://github.com/nail-dp-dev/Nail_dp_dev_FE/assets/121030294/cd916237-ebed-426c-8d14-a1aed68fbc2d)

**Comment by Ju-jh** [comment]
#10 Completed.

**Comment by lsh7465** [comment]
colors 설정 완료.
![Image](https://github.com/nail-dp-dev/nail-dp-dev-nextjs14/assets/155132402/2548db66-7f2b-4dd5-95a0-55005275b4e4)
